baseURL = "https://www.example.org/"
languageCode = "en-us"
theme = "aafu"

[params]
    title = "Aafu theme"
    author = "PRAVEEN"
    description = "Website title"
    copyright = "aaa"

    [params.theme]
        # Available themes are 'light', 'dark', and 'pinkish'
        mainTheme = "pinkish"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = true
        singlePage = false

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "PRAVEEN.A"
		tagline = "R Programmer"
		location = "Coimbatore"
        photo = "profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            class = "fab"
            icon = "fa-linkedin-in"
            url = "https://www.linkedin.com/in/praveen-arumugam-a05b03173/"
            title = "LinkedIn"		
        [[params.social.list]]
            class = "fab"
            icon = "fa-stack-overflow"
            url = "#"
            title = "StackOverflow"
        [[params.social.list]]
            class = "fab"
            icon = "fa-github"
            url = "#"
            title = "GitHub"
        [[params.social.list]]
            class = "fab"
            icon = "fa-twitter"
            url = "#"
            title = "Twitter"
		[[params.social.list]]
            class = "ai"
            icon = "ai-google-scholar"
            url = "#"
            title = "Google Scholar"
		[[params.social.list]]
            class = "ai"
            icon = "ai-researchgate"
            url = "#"
            title = "ResearchGate"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "publication"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "Seeking a position of data analyst with the use of analytical thinking and relevant expertise to help the organization understand its longterm goals."

    # Experience section
    [params.experience]
        title = "Experiences"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "*Junior Wordpress Developer*"
            dates = "Sep 2019 - Mar 2020"
            company = "iGlitz Technologies, Coimbatore"
            details = "Created Websites for the Company using Wordpress."

     
    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "**Bachelor of Engineering (B.E), Computer Science**"
            college = "KPR Institute of Engineering and Technology"
            dates = "2015 - 2019"
            college_link = "https://www.kpriet.ac.in/"
        [[params.education.list]]
            degree = "**Senior Secondary (XII)**"
            college = "Mani Higher Secondary School"
            dates = "2013 - 2015"
            
        [[params.education.list]]
            degree = "**Secondary (X)**"
            college = "Mani Higher Secondary School"
            dates = "2012 - 2013"

    # Certification section
    [params.certificate]
        title = "Certifications"
        icon = "fas fa-book"
        

        [[params.certificate.list]]
            title = "Data Analyst with R"
            organization = "Datacamp"
      
        [[params.certificate.list]]
            title = "Data Science with R"
            organization = "Datacamp"
        [[params.certificate.list]]
            title = "SQL Masterclass : SQL for Data Analytics"
            organization = "Udemy"
        [[params.certificate.list]]
            title = "Shiny Fundamentals with R"
            organization = "Datacamp"
        [[params.certificate.list]]
            title = "Tableau Training : Master Tableau for Data Science"
            organization = "Udemy"
         [[params.certificate.list]]
            title = "R programming"
            organization = "Internshala"
        [[params.certificate.list]]
            title = "MATLAB Onramp"
            organization = "MATLAB"

    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "**Exploring The Kaggle Data Science Survey**"
            url = "#"
            description = "In this project we nd what tools and languages professionals are using in theirdaily work. Our data comes from the Kaggle Data Science Survey, which includes responses from over 10,000 people who write code for analyzing data in everyday work."
        [[params.project.list]]
            title = "**Level Diculty In Candy Crush Saga**"
            url = "#"
            description = "In this project, we will see how we can use data collected from players to estimate level diculty using R programming."
        [[params.project.list]]
            title = "**COVID-19 DASHBOARD**"
            url = "https://public.tableau.com/profile/praveen.a2733#!/vizhome/covid_15959282046660/Dashboard1"
        [[params.project.list]]
            title = "**KPMG-Data-Analytics-Virtual-Internship**"
            url = "https://public.tableau.com/profile/praveen.a2733#!/vizhome/Data3_15961159849010/Dashboard1"
            description = "Customer Segmentation Using RFM"

    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "R-Programming"
            skillrating = 90
        [[params.skill.list]]
            skill = "Tableau"
            skillrating = 80
        [[params.skill.list]]
            skill = "R-Shiny"
            skillrating = 70
        [[params.skill.list]]
            skill = "Wordpress"
            skillrating = 80
        [[params.skill.list]]
            skill = "Figma"
            skillrating = 70
        [[params.skill.list]]
            skill = "Tableau_Prep"
            skillrating = 60
         [[params.skill.list]]
            skill = "SQL"
            skillrating = 50

    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"
		
        [[params.hobby.list]]		
		    hobby = "Cooking"
        [[params.hobby.list]]		
		    hobby = "Hiking"
        [[params.hobby.list]]		
		    hobby = "Baking"
		  
		  # Area of Interest section
    [params.aoi]
        title = "Area of Interest"
        icon = "fas  fa-plus-circle"
		
        [[params.aoi.list]]		
		    aoi = "Data Analytics"
        [[params.aoi.list]]		
		    aoi = "Machine Learning"
        [[params.aoi.list]]		
		    aoi = "Deep Learning"
		    [[params.aoi.list]]		
		    aoi = "Web Apps R"
